
server {

    listen 8002;
    server_name localhost;

    listen 1004;
    root /absolute/path/to/docs/fusion_web/;
    client_max_body_size 3000000;  # 올바른 지시어
    index index.html;
    error_page 404 /error_pages/404.html;

    location / {
        # allow_methods  DELETE POST GET; (잘못된 지시어)
        autoindex off;
    }
    location /tours {
        autoindex on;
        index tours1.html;
           # allow_methods GET POST PUT HEAD; (잘못된 지시어)
    }

    location /red {
        return 301 /tours;  # 301 리다이렉션 사용
    }

    location /cgi-bin {
        root /absolute/path/to/;  # 절대 경로 사용
        # allow_methods GET POST DELETE; (잘못된 지시어)
        index time.py;
        # cgi_path /usr/bin/python3 /bin/bash; (잘못된 지시어)
        # cgi_ext .py .sh; (잘못된 지시어)
    }
}

server {

    listen 8080;

    server_name localhost;

    root /absolute/path/to/docs/fusion_web/;
    client_max_body_size 12341234;  # 올바른 지시어
    index index.html;
    error_page 403 /error_pages/403.html;
}
