
server {

    listen 1004;
    server_name localhost;
    client_max_body_size 3000000;
    allowed_methods GET POST DELETE;
    index index.html;

    location / {
        root /Users/haejeong/goinfre/webserv/html/;
        index index.html;
        allowed_methods GET;
    }

    location /image {
        root /Users/haejeong/goinfre/webserv/image/;   
    }
}
