
server {

    listen 1004;
    server_name localhost;
    client_max_body_size 3000000;
    allowed_methods GET POST DELETE;

    location / {
        root /Users/haejeong/goinfre/webserv2/html/;
        index index.html;
        allowed_methods GET; 
    }

    location /test {
        root /Users/haejeong/goinfre/webserv2/html/;
        index index.html;
    }

    GET /test HTTP/1.1
        -> 301 redirection /test/

    GET /test/ HTTP/1.1
        /test index.html
}
